DEFAULT_DEBATER_ONE_NAME = "Debater_One"
DEFAULT_DEBATER_TWO_NAME = "Debater_Two"
DEFAULT_JUDGE_NAME = "Judge"
DEFAULT_BACKGROUND_TEXT = "None provided"
DEFAULT_WORD_LIMIT = 750
INSTRUCTION_PREFIX = "[INST]"
INPUT_PREFIX = "### User:"
INSTRUCTION_SUFFIX = "[/INST]"
